### PR TITLE
Fix for WIN32 and WIN64 build with Linux MinGW cross-compiler

### PR DESCRIPTION
**Pull request by stan0x**

### CODE REVIEW

**Review by Raptor007 — COMMENTED** [review]
Unfortunately setting `CC=i686-w64-mingw32-gcc` is only applicable to MinGW64, not the original MinGW environment.  This would break other people's builds.  In general the default compiler should just be `gcc` outside of the special circumstance of cross-compiling.

If you let me know what `uname -s` says on your system, we can use that information to improve upon the MinGW/Cygwin detection, which is not currently detecting your MinGW64 correctly.  That specific condition could also set `CC=i686-w64-mingw32-gcc` as the default compiler when `WIN64` is not defined.

The name `WIN32` applies to both the 32-bit and 64-bit builds in this case, as it also sets the `-DWIN32` flag for the `#ifdef WIN32` checks in tng_irc.c.  That's why the `SHLIBLIBS=-lws2_32` and `SHLIBEXT=dll` were not set within the `WIN64` section, although there's no harm in repeating those settings.

**Comment by stan0x** [comment]
This is what uname -s says.

quake2@Ubuntu:~$ uname -s
Linux

**Comment by Raptor007** [comment]
Ah, so it's cross-compiling, not the MinGW Windows environment.  That explains why it didn't set `WIN32=y` automatically.

Usually cross-compilation is achieved by `make CC=whatever-gcc` but I think this is a common enough use case for the Makefile to attempt automatic detection, perhaps with something like `$(shell which i686-w64-mingw32-gcc)` to see if a relevant cross-compiler is available.

**Review by Raptor007 — APPROVED** [review]
I'm going to make another tweak immediately after this to prevent the WIN32 `CC=i686-w64-mingw32-gcc` line from effecting builds that aren't cross-compiled.

**Pull request merged**
