### PR TITLE
Sync serverinfo master

### PR DESCRIPTION
**Pull request by darkshade9**
Suggest to merge https://github.com/Raptor007/aq2-tng/pull/134 first before this one, it will be a bit cleaner

### CODE REVIEW

**Comment by Raptor007** [comment]
I see one small problem.  Domination is a game mode, not a flag.

This is correctly handled in g_spawn.c, but it looks like g_local.h and tng_stats.c should be tweaked.  I don't see the `Gamemode()` function actually called anywhere, so maybe the only effect of this is that Domination games will set gmf bit 2 in addition to showing gm=dom.

**Comment by darkshade9** [comment]
Ah yeah, I now realize this was a 2-part PR and I only grabbed the first part.

I was basing some of the mode/flag logic around what could and couldn't be enabled based on the `g_spawn.c` statement tree.  `dom` requires `teamplay` on, `teamdm` and `use_tourney` off.  I'll make the appropriate changes.

`Gamemode()` is used with stat collection but it is unique to AQtion, I will remove it here.

I will also update the `strcpy` items to use `Q_strncpyz` in `g_spawn.c` to mimic what is done in `a_game.c`

**Comment by darkshade9** [comment]
For clarification, we're using the gamemode and gamemode flags heavily in stat collection, moving all other game mode flags down a peg (4->2, 8->4) would cause a ton of work.  We've some ideas for creating new game modes anyway, so I'll leave it in there as a placeholder

**Comment by Raptor007** [comment]
Looks good, thanks!  You did exactly what I would have done, which is just retire gmf bit 2 for now until you have another use for it.

Just FYI, the main reason to use functions like `Q_strncpyz` rather than `strcpy` is to ensure inputs of unknown length can never overflow the destination buffer.  Those fixed-length default values would never be at risk of this.  But there's no harm in the change either.

**Pull request merged**
