### PR TITLE
Add raspberry pi 4 support

### PR DESCRIPTION
**Pull request by stan0x**
Fix for for compile on ubuntu server for pi 4 arch.

### CODE REVIEW

**Review by Raptor007 — COMMENTED** [review]
Looks good to me.  Is the value of `uname -m` just `aarch64`?  I'm thinking it would be better to get away from all these exceptions by generally setting `ARCH=$(MACHINE)` and just change it to `ARCH=x86` on Windows MinGW, which I think is the only platform where those don't match.

**Comment by stan0x** [comment]
`uname -a`
`Linux stan0x-desktop 5.8.0-1010-raspi #13-Ubuntu SMP PREEMPT Wed Dec 9 17:14:07 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux`

U may choose. This was my way to fix it. If u have a beter sulotion its ok by me.

**Comment by Raptor007** [comment]
Thanks!  For now I'll just merge yours since it looks like a nice quick fix.

Issue #73 already had me considering the mess of architecture detection in the Makefile, and your pull kind of confirmed for me that it should generally use `ARCH=$(MACHINE)` and just make an exception for Windows, so I will probably overhaul this part of the Makefile soon.

**Comment by Raptor007** [comment]
Since it was on my mind and a quick job, I cleaned up the Makefile today: https://github.com/Raptor007/aq2-tng/commit/58f7790aa78c8e68244ccb148fbf5e2732769fce

Let me know if this causes any issues on the Raspberry Pi 4 (or other platforms).

**Comment by stan0x** [comment]
It works only if i define NO_BOTS while compiling on the raspberry pi4.

If  just type make it fails compiling.

i getting these errors.

cc -Wall -fno-strict-aliasing -DC_ONLY -DVERSION="\"2.81 2021-01-04 6d7e637\"" -O2 -fPIC  -o acesrc/botchat.o -c acesrc/botchat.c
cc -Wall -fno-strict-aliasing -DC_ONLY -DVERSION="\"2.81 2021-01-04 6d7e637\"" -O2 -fPIC  -o acesrc/botnav.o -c acesrc/botnav.c
cc -Wall -fno-strict-aliasing -DC_ONLY -DVERSION="\"2.81 2021-01-04 6d7e637\"" -O2 -fPIC  -o acesrc/acebot_movement.o -c acesrc/acebot_movement.c
cc -Wall -fno-strict-aliasing -DC_ONLY -DVERSION="\"2.81 2021-01-04 6d7e637\"" -O2 -fPIC  -o acesrc/bot_collision.o -c acesrc/bot_collision.c
cc -Wall -fno-strict-aliasing -DC_ONLY -DVERSION="\"2.81 2021-01-04 6d7e637\"" -O2 -fPIC  -o acesrc/botscan.o -c acesrc/botscan.c
cc -Wall -fno-strict-aliasing -DC_ONLY -DVERSION="\"2.81 2021-01-04 6d7e637\"" -O2 -fPIC -shared -o gameaarch64.so a_cmds.o a_ctf.o a_doorkick.o a_game.o a_items.o a_match.o a_menu.o a_radio.o a_team.o a_tourney.o a_vote.o a_xcmds.o a_xgame.o a_xmenu.o a_xvote.o cgf_sfx_glass.o g_chase.o g_cmds.o g_combat.o g_func.o g_items.o g_main.o g_misc.o g_phys.o g_save.o g_spawn.o g_svcmds.o g_target.o g_trigger.o g_utils.o g_weapon.o p_client.o p_hud.o p_view.o p_weapon.o q_shared.o tng_stats.o tng_flashlight.o tng_irc.o tng_ini.o tng_balancer.o g_grapple.o a_dom.o tng_jump.o acesrc/acebot_ai.o acesrc/acebot_nodes.o acesrc/bot_combat.o acesrc/bot_states.o acesrc/acebot_cmds.o acesrc/acebot_spawn.o acesrc/bot_env_doors.o acesrc/bot_utility.o acesrc/acebot_compress.o acesrc/bot_ai.o acesrc/bot_movement.o acesrc/bot_weapon.o acesrc/acebot_items.o acesrc/botchat.o acesrc/botnav.o acesrc/acebot_movement.o acesrc/bot_collision.o acesrc/botscan.o
/usr/bin/ld: a_ctf.o:(.bss+0x140): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: a_ctf.o:(.bss+0x148): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: a_doorkick.o:(.bss+0x0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: a_doorkick.o:(.bss+0x8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: a_game.o:(.bss+0x2410): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: a_game.o:(.bss+0x2418): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: a_items.o:(.bss+0x0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: a_items.o:(.bss+0x8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: a_match.o:(.bss+0x8): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: a_match.o:(.bss+0x10): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: a_menu.o:(.bss+0x0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: a_menu.o:(.bss+0x8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: a_radio.o:(.bss+0x0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: a_radio.o:(.bss+0x8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: a_team.o:(.bss+0x83e8): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: a_team.o:(.bss+0x83f0): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: a_tourney.o:(.bss+0x194c0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: a_tourney.o:(.bss+0x194c8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: a_vote.o:(.bss+0x890): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: a_vote.o:(.bss+0x898): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: a_xcmds.o:(.bss+0x80): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: a_xcmds.o:(.bss+0x88): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: a_xgame.o:(.bss+0x0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: a_xgame.o:(.bss+0x8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: a_xmenu.o:(.bss+0x0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: a_xmenu.o:(.bss+0x8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: a_xvote.o:(.bss+0x0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: a_xvote.o:(.bss+0x8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: cgf_sfx_glass.o:(.bss+0x20): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: cgf_sfx_glass.o:(.bss+0x28): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: g_chase.o:(.bss+0x0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: g_chase.o:(.bss+0x8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: g_cmds.o:(.bss+0x280): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: g_cmds.o:(.bss+0x288): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: g_combat.o:(.bss+0x0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: g_combat.o:(.bss+0x8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: g_func.o:(.bss+0x0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: g_func.o:(.bss+0x8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: g_items.o:(.bss+0xc8): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: g_items.o:(.bss+0xd0): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: g_main.o:(.bss+0x6ff8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: g_main.o:(.bss+0x6ff0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: g_misc.o:(.bss+0x0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: g_misc.o:(.bss+0x8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: g_phys.o:(.bss+0x8010): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: g_phys.o:(.bss+0x8018): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: g_save.o:(.bss+0x0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: g_save.o:(.bss+0x8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: g_spawn.o:(.bss+0x9870): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: g_spawn.o:(.bss+0x9878): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: g_svcmds.o:(.bss+0x3008): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: g_svcmds.o:(.bss+0x3010): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: g_target.o:(.bss+0x0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: g_target.o:(.bss+0x8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: g_trigger.o:(.bss+0x8): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: g_trigger.o:(.bss+0x10): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: g_utils.o:(.bss+0x170): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: g_utils.o:(.bss+0x178): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: g_weapon.o:(.bss+0x8): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: g_weapon.o:(.bss+0x10): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: p_client.o:(.bss+0x10): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: p_client.o:(.bss+0x18): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: p_hud.o:(.bss+0x0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: p_hud.o:(.bss+0x8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: p_view.o:(.bss+0x58): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: p_view.o:(.bss+0x60): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: p_weapon.o:(.bss+0x8): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: p_weapon.o:(.bss+0x10): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: tng_stats.o:(.bss+0x0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: tng_stats.o:(.bss+0x8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: tng_flashlight.o:(.bss+0x0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: tng_flashlight.o:(.bss+0x8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: tng_irc.o:(.bss+0x2870): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: tng_irc.o:(.bss+0x2878): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: tng_ini.o:(.bss+0x468): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: tng_ini.o:(.bss+0x470): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: tng_balancer.o:(.bss+0x10): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: tng_balancer.o:(.bss+0x18): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: g_grapple.o:(.bss+0x8): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: g_grapple.o:(.bss+0x10): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: a_dom.o:(.bss+0x48): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: a_dom.o:(.bss+0x50): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: tng_jump.o:(.bss+0x0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: tng_jump.o:(.bss+0x8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: acesrc/acebot_ai.o:(.bss+0x0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: acesrc/acebot_ai.o:(.bss+0x8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: acesrc/acebot_nodes.o:(.bss+0x2e11c8): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: acesrc/acebot_nodes.o:(.bss+0x2e11d0): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: acesrc/bot_combat.o:(.bss+0x0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: acesrc/bot_combat.o:(.bss+0x8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: acesrc/bot_states.o:(.bss+0x0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: acesrc/bot_states.o:(.bss+0x8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: acesrc/acebot_cmds.o:(.bss+0x10): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: acesrc/acebot_cmds.o:(.bss+0x8): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: acesrc/acebot_spawn.o:(.bss+0x190): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: acesrc/acebot_spawn.o:(.bss+0x198): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: acesrc/bot_env_doors.o:(.bss+0x0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: acesrc/bot_env_doors.o:(.bss+0x8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: acesrc/bot_utility.o:(.bss+0x0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: acesrc/bot_utility.o:(.bss+0x8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: acesrc/bot_ai.o:(.bss+0x0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: acesrc/bot_ai.o:(.bss+0x8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: acesrc/bot_movement.o:(.bss+0x0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: acesrc/bot_movement.o:(.bss+0x8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: acesrc/bot_weapon.o:(.bss+0x0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: acesrc/bot_weapon.o:(.bss+0x8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: acesrc/acebot_items.o:(.bss+0x6808): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: acesrc/acebot_items.o:(.bss+0x6810): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: acesrc/botchat.o:(.bss+0x0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: acesrc/botchat.o:(.bss+0x8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: acesrc/botnav.o:(.bss+0x1c28): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: acesrc/botnav.o:(.bss+0x1c30): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: acesrc/acebot_movement.o:(.bss+0x8): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: acesrc/acebot_movement.o:(.bss+0x10): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
/usr/bin/ld: acesrc/bot_collision.o:(.bss+0x0): multiple definition of `real_centerprintf'; a_cmds.o:(.bss+0x0): first defined here
/usr/bin/ld: acesrc/bot_collision.o:(.bss+0x8): multiple definition of `real_cprintf'; a_cmds.o:(.bss+0x8): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:118: gameaarch64.so] Error 1

**Comment by Raptor007** [comment]
Aha!  That doesn't seem to be caused by the Makefile changes, but was an existing issue in the bot code.  The definition of `real_centerprintf` is in game.h so it's adding the symbol to every object.  It should be in one of the .c files instead, probably with an `extern` in game.h.  I'll get that sorted out.

**Comment by Raptor007** [comment]
Try it now: https://github.com/Raptor007/aq2-tng/commit/2d9c85d71e9546fff2438cc221446de6f0890077

**Comment by stan0x** [comment]
yes thats fixxed it.

since be bussy now. can you fix the [-Wformat-truncation=] errors ?

if i use gcc-7 they are gone.

**Comment by stan0x** [comment]
changing this in make file did removed the  [-Wformat-truncation=] errors ?

`CC=gcc-7`
`BASE_CFLAGS=-Wall -Wno-format-truncation -fno-strict-aliasing -DC_ONLY -DVERSION="\"$(VERSION)\""`

Only got these left.

gcc-7 -Wall -Wno-format-truncation -fno-strict-aliasing -DC_ONLY -DVERSION="\"2.81 2021-01-07 2d9c85d\"" -O2 -fPIC  -o acesrc/acebot_ai.o -c acesrc/acebot_ai.c
gcc-7 -Wall -Wno-format-truncation -fno-strict-aliasing -DC_ONLY -DVERSION="\"2.81 2021-01-07 2d9c85d\"" -O2 -fPIC  -o acesrc/acebot_nodes.o -c acesrc/acebot_nodes.c
acesrc/acebot_nodes.c: In function ‘ACEND_LoadNodes’:
acesrc/acebot_nodes.c:1343:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(&version,sizeof(int),1,pIn); // read version
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
acesrc/acebot_nodes.c:1349:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread(&numnodes,sizeof(int),1,pIn); // read count
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
acesrc/acebot_nodes.c:1350:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread(&num_items,sizeof(int),1,pIn); // read facts count
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
acesrc/acebot_nodes.c:1352:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread(nodes,sizeof(node_t),numnodes,pIn);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
acesrc/acebot_nodes.c:1356:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(&path_table[i][j],sizeof(short int),1,pIn); // write count
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
acesrc/acebot_nodes.c:1358:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
   fread(item_table,sizeof(item_table_t),num_items,pIn);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc-7 -Wall -Wno-format-truncation -fno-strict-aliasing -DC_ONLY -DVERSION="\"2.81 2021-01-07 2d9c85d\"" -O2 -fPIC  -o acesrc/bot_combat.o -c acesrc/bot_combat.c
gcc-7 -Wall -Wno-format-truncation -fno-strict-aliasing -DC_ONLY -DVERSION="\"2.81 2021-01-07 2d9c85d\"" -O2 -fPIC  -o acesrc/bot_states.o -c acesrc/bot_states.c
gcc-7 -Wall -Wno-format-truncation -fno-strict-aliasing -DC_ONLY -DVERSION="\"2.81 2021-01-07 2d9c85d\"" -O2 -fPIC  -o acesrc/acebot_cmds.o -c acesrc/acebot_cmds.c
gcc-7 -Wall -Wno-format-truncation -fno-strict-aliasing -DC_ONLY -DVERSION="\"2.81 2021-01-07 2d9c85d\"" -O2 -fPIC  -o acesrc/acebot_spawn.o -c acesrc/acebot_spawn.c
acesrc/acebot_spawn.c: In function ‘ACESP_LoadBotConfig’:
acesrc/acebot_spawn.c:182:2: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
  fgets( inString, 80, pIn );
  ^~~~~~~~~~~~~~~~~~~~~~~~~~
gcc-7 -Wall -Wno-format-truncation -fno-strict-aliasing -DC_ONLY -DVERSION="\"2.81 2021-01-07 2d9c85d\"" -O2 -fPIC  -o acesrc/bot_env_doors.o -c acesrc/bot_env_doors.c
gcc-7 -Wall -Wno-format-truncation -fno-strict-aliasing -DC_ONLY -DVERSION="\"2.81 2021-01-07 2d9c85d\"" -O2 -fPIC  -o acesrc/bot_utility.o -c acesrc/bot_utility.c
gcc-7 -Wall -Wno-format-truncation -fno-strict-aliasing -DC_ONLY -DVERSION="\"2.81 2021-01-07 2d9c85d\"" -O2 -fPIC  -o acesrc/acebot_compress.o -c acesrc/acebot_compress.c
acesrc/acebot_compress.c: In function ‘Decode’:
acesrc/acebot_compress.c:234:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(&version,sizeof(int),1,pIn); // read version
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
acesrc/acebot_compress.c:235:2: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(&version,sizeof(int),1,pIn); // read buffersize (not needed, so repeat into version)
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc-7 -Wall -Wno-format-truncation -fno-strict-aliasing -DC_ONLY -DVERSION="\"2.81 2021-01-07 2d9c85d\"" -O2 -fPIC  -o acesrc/bot_ai.o -c acesrc/bot_ai.c
gcc-7 -Wall -Wno-format-truncation -fno-strict-aliasing -DC_ONLY -DVERSION="\"2.81 2021-01-07 2d9c85d\"" -O2 -fPIC  -o acesrc/bot_movement.o -c acesrc/bot_movement.c
gcc-7 -Wall -Wno-format-truncation -fno-strict-aliasing -DC_ONLY -DVERSION="\"2.81 2021-01-07 2d9c85d\"" -O2 -fPIC  -o acesrc/bot_weapon.o -c acesrc/bot_weapon.c

**Pull request merged**
