### PR TITLE
Mapvote time next

### PR DESCRIPTION
**Pull request by darkshade9**
Realized my file encoding is screwed up again (thanks VScode!) I will make this PR ready once I've resolved that

### CODE REVIEW

**Comment by Raptor007** [comment]
That's funny, I often `votemap` at the last second so it doesn't make other players think that I want to change maps immediately, and to prevent accidentally ending the map early if it's just me and bots.

This looks like a good feature, but I would tweak it a tiny bit:
1. Instead of using `mapvote_next 2` I'd just make the default `mapvote_next_time 0`.  If set to non-zero, then it restricts last-second votes by that amount.  (Replace `mapvote_next->value == 2` with `mapvote_next_time->value` [in the `if` condition](https://github.com/Raptor007/aq2-tng/pull/128/files#diff-ce895d5967710701f3d65115fc5fd7e1b512e186c4649e24dd35d0074e332a92R182) and revert the documentation of votemap_next to what it was before.)
2. Since it seems this limitation applies to last-second voting even without `mapvote_next` it might be clearer to rename it.  Maybe something like `mapvote_lastsec`?  Or if you prefer to keep it `mapvote_next_time` that's fine with me.

Sorry that I have not responded to the latest few issues yet.  This weekend is the big push for us moving to a new house!  I should have more time to deal with AQ2 stuff next week.  :-)

**Comment by darkshade9** [comment]
- Renamed to `mapvote_next_limit`
- Default is `0`
- Enforced if `mapvote_next` is `1` (removed the `2` condition)

**Comment by darkshade9** [comment]
In your first use case, where you change the next map using this feature, would it make sense to create an additional var, like `mapvote_force <mapname>` which you can call via rcon to override what the next map is, but is also overridden if there's a playervote?  That way you maintain that functionality while also protecting from last second aq2soccer voters?

**Comment by darkshade9** [comment]
> Sorry that I have not responded to the latest few issues yet. This weekend is the big push for us moving to a new house! I should have more time to deal with AQ2 stuff next week. :-)

No problem man, real life takes real time, no avoiding it, but hopefully the new pad is a great upgrade :)  We'd love to chat with you more in Discord if you can make it, we're getting stats/achievements online soon, ladders are coming, tournaments around the corner, we're hoping for a strong Fall/Winter when everyone comes inside and has nothing else to do :)

**Pull request merged**
